### ISSUE TITLE
В методе containsGame условия в цикле не выполняются

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#1]
# Описание
Счетчик цикла равен размеру коллекции из одного элемента, так что i не может быть меньше размера коллекции из одного элемента.

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/GameStore.java#L33) в IDEA.
2. Запустить [тест](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/test/java/ru/netology/GameStoreTest.java#L8-L15) shouldAddGame

*Ожидаемый результат:* Метод проверяет наличие добавленной игры в коллекции, выводит true.
*Фактический результат:* В консоли появляется ошибка false, что значит, что такой игры нет в каталоге.

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/179419358-9d0d4011-d43e-425b-b84e-572f71000fad.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_5](https://user-images.githubusercontent.com/104067981/180417145-78b41083-97b3-4b9c-88b2-771d4a79b648.jpg)
