### ISSUE TITLE
Метод sumGenre не суммирует время, если игра повторяется (переустановлена)

### ISSUE THREAD

**Issue by FairyGreta** [unicornfraaa/Java---TeamProject#10]
# Описание
Метод sumGenre не суммирует время, если игра повторяется (переустановлена)

# Локация
[https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L45-L55](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L45-L55)

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L45-L55) в IDEA;
1. Запустить тест shouldAddDoubleGame

_Ожидаемый результат_: метод выдаст сумму 2
_Фактический результат_: метод не суммирует и выдает 0

# Скриншот
![Screenshot_2](https://user-images.githubusercontent.com/104067981/179956506-ac9b72f7-ed3c-4adf-b239-e29874cc69a7.jpg)

# Окружение
- **Операционная система**: Windows 10 Домашняя
- **IDE**: IntelliJ IDEA Community Edition 2022.1.2
- **Java**: OpenJDK 11

**Comment by unicornfraaa** [comment]
fixed
![image](https://user-images.githubusercontent.com/105659262/180235751-2e272b0e-ee00-4756-bcce-b83d52a87107.png)
