### ISSUE TITLE
Не выкидывается исключение, если дублировать установку игры

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#11]
# Описание
Не выкидывается исключение, если дублировать установку одной и той же игры

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/2db72c6060a8fd45bb2fc746b8bcae20921dc341/src/main/java/ru/netology/GameStore.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/2db72c6060a8fd45bb2fc746b8bcae20921dc341/src/main/java/ru/netology/GameStore.java#L22-L26) в IDEA.
1. Запустить [тест](https://github.com/unicornfraaa/Java---TeamProject/blob/e5401b61c8db7ece581276e0473dc90f6bddf4de/src/test/java/ru/netology/GameStoreTest.java#L77-L88) shouldAddDuplicated

*Ожидаемый результат:* Метод выкидывает исключение.
*Фактический результат:* В консоли появляется ошибка org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/180431633-55704b5d-0002-4e53-bfb9-a154a57b7d3e.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_2](https://user-images.githubusercontent.com/104067981/180601195-eb03c87a-a48e-4ee1-a1c0-4cfffc1a7583.jpg)
