### ISSUE TITLE
Если кол-во часов менее 1 часа(включительно), то работа метода getMostPlayer ломается

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#12]
# Описание
Если кол-во часов менее 1 часа(включительно), то работа метода getMostPlayer ломается

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/d766f49c0f46bd7b8506dd0a4baffd504e2e98ff/src/test/java/ru/netology/GameStoreTest.java#L95
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/2db72c6060a8fd45bb2fc746b8bcae20921dc341/src/main/java/ru/netology/GameStore.java#L46-L52) в IDEA.
1. Запустить [тест](https://github.com/unicornfraaa/Java---TeamProject/blob/d766f49c0f46bd7b8506dd0a4baffd504e2e98ff/src/test/java/ru/netology/GameStoreTest.java#L90-L100) shouldAddPlayerTimeLessThanOneHour

*Ожидаемый результат:* Возвращает значение "{"Kirill"}"
*Фактический результат:* Возвращает массив с двумя игроками

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/180433992-392ae52a-5512-468b-b51b-62d1d23e2b1f.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_3](https://user-images.githubusercontent.com/104067981/180601214-182afa83-0015-4115-9b45-2397b333daa7.jpg)
