### ISSUE TITLE
Метод getMostPlayer возвращает массив игроков, которые не играли

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#13]
# Описание
Игроки не играли, метод getMostPlayer возвращает массив из них вместо null.

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/01bbde7ee97d5beea9e20c03998071cffcdc6261/src/test/java/ru/netology/GameStoreTest.java#L107

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/2db72c6060a8fd45bb2fc746b8bcae20921dc341/src/main/java/ru/netology/GameStore.java#L58-L69) в IDEA.
1. Запустить [тест](https://github.com/unicornfraaa/Java---TeamProject/blob/01bbde7ee97d5beea9e20c03998071cffcdc6261/src/test/java/ru/netology/GameStoreTest.java#L103-L112) shouldReturnNullMostPlayer

*Ожидаемый результат:* Метод выкидывает null.
*Фактический результат:* Выдает массив игроков.

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/180435623-87ddba32-fae9-42a8-8a45-8847e24f98e7.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_4](https://user-images.githubusercontent.com/104067981/180601236-8cae260a-8fcb-47b4-b01f-a478169163d1.jpg)
