### ISSUE TITLE
Метод getMostPlayer не определяет игрока с наибольшим временем игры, если время меньше или равно 1 часу игры

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#2]
# Описание
В методе getMostPlayer сумма наигранных часов игроком (playerTime)  сравнивается с 1 часом (mostTime).
Если playerTime >1, то условие проходит. Нужно сравнивать с нулем, либо в условии сравнения (mostTime) поставить ">=", чтобы игрок с суммой  = 1 час тоже выводился в результат.

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/3181f589d10a5d1eb5f83731229abdf63692770e/src/main/java/ru/netology/GameStore.java#L59

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/3181f589d10a5d1eb5f83731229abdf63692770e/src/main/java/ru/netology/GameStore.java#L58-L69) в IDEA.
2. Запустить [тест](https://github.com/unicornfraaa/Java---TeamProject/blob/3181f589d10a5d1eb5f83731229abdf63692770e/src/test/java/ru/netology/GameStoreTest.java#L17-L30) shouldAddPlayerTime

Ожидаемый результат: Возвращает значение "Kirill"
Фактический результат: Возвращает null

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/179420337-c775e072-bfad-47b0-a31e-8ac7aa0f8209.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_4](https://user-images.githubusercontent.com/104067981/180416878-1d28ade1-5d46-452a-9bf3-35d350f88061.jpg)
