### ISSUE TITLE
Метод getSumPlayedTime не считает количество наигранных часов и всегда возвращает 0 часов

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#3]
# Описание
Метод getSumPalyedTime не дописан, возвращает только 0 по логике.

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/3181f589d10a5d1eb5f83731229abdf63692770e/src/main/java/ru/netology/GameStore.java#L76

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/3181f589d10a5d1eb5f83731229abdf63692770e/src/main/java/ru/netology/GameStore.java#L75-L77) в IDEA.

2. Запустить [тест](https://github.com/unicornfraaa/Java---TeamProject/blob/2bf0808cc4f703f2917704af3229a784a17c8971/src/test/java/ru/netology/GameStoreTest.java#L31-L43) shouldSumPlayerTime

*Ожидаемый результат:* Возвращает общее количество наигранных часов (3).
*Фактический результат:* Возвращает 0 часов.

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/179422092-2f3743ee-8e2a-410a-9189-c76cf0c3be30.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_2](https://user-images.githubusercontent.com/104067981/180232326-6b847845-7d83-48c6-b9d8-fb45c0453aa3.jpg)

**Comment by FairyGreta** [comment]
fixed
![Screenshot_1](https://user-images.githubusercontent.com/104067981/180402391-f5f8989d-a48f-4c38-aca0-5a9323bce2ba.jpg)
