### ISSUE TITLE
Метод addPlayTime не суммирует количество наигранных часов 

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#4]
#  Описание
Метод addPlayTime  не суммирует наигранные часы при добавлении нового количества часов (hours) зарегистрированному игроку из-за некорректной логики метода getSumPlayedTime.

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/2bf0808cc4f703f2917704af3229a784a17c8971/src/main/java/ru/netology/GameStore.java#L48

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/2bf0808cc4f703f2917704af3229a784a17c8971/src/main/java/ru/netology/GameStore.java#L46-L52) в IDEA.
2. Запустить [тест](https://github.com/OlegFilippoff/teamTask/blob/092eed6c73d0c1482953a4444cbd3a04ddace121/src/test/java/ru/netology/GameStoreTest.java#L82-L97) shouldAddPlayerTimeToTime

*Ожидаемый результат:* Возвращает количество наигранных часов игроками (10).
*Фактический результат:* Возвращает 0.

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/179422325-0ecdce06-dcd7-4a43-a276-48576c8a4b03.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_3](https://user-images.githubusercontent.com/104067981/180233923-48dc0f30-b573-45be-b92b-eb1f3d01ceec.jpg)
