### ISSUE TITLE
Метод getMostPlayer возвращает одного игрока, даже если наиграно равное время

### ISSUE THREAD

**Issue by unicornfraaa** [unicornfraaa/Java---TeamProject#5]
# Описание
Метод getMostPlayer возвращает одного игрока, даже если наиграно равное время 

# Локация дефекта
https://github.com/unicornfraaa/Java---TeamProject/blob/99f17de60371f60cebab777168bc51949dfd81af/src/main/java/ru/netology/GameStore.java#L68

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/99f17de60371f60cebab777168bc51949dfd81af/src/main/java/ru/netology/GameStore.java#L58-L69) в IDEA.
2. Запустить [тест](https://github.com/unicornfraaa/Java---TeamProject/blob/8ff149441fabef1065fb4d8c1e2cb2f7f74651d2/src/test/java/ru/netology/GameStoreTest.java#L62-L77) equalPlayedTime

*Ожидаемый результат:* Возвращает значение "{"Petya", "Kirill"}"
*Фактический результат:* Возвращает ошибку "org.opentest4j.AssertionFailedError: array lengths differ, expected: <2> but was: <1>"

# Скриншот
![image](https://user-images.githubusercontent.com/105659262/179490886-7e89ece1-1b3e-4047-95e6-d227e68dc988.png)

# Окружение
* **Операционная система:** Windows 11 Домашняя
* **IDE:** IntelliJ IDEA Community Edition 2022.1.2
* **Java:** OpenJDK 11

**Comment by FairyGreta** [comment]
fixed
![Screenshot_4](https://user-images.githubusercontent.com/104067981/180416965-7b768f98-90f9-45c2-81f3-eeb040cc8481.jpg)
