### ISSUE TITLE
Метод sumGenre не суммирует время, проигранное во все игры одного жанра, если несколько игр

### ISSUE THREAD

**Issue by FairyGreta** [unicornfraaa/Java---TeamProject#7]
# Описание
Метод sumGenre не суммирует время, проигранное игроком во все игры одного жанра, если игр две и более

# Локация
[https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L49](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L49)

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L45-L54) в IDEA;
1. Запустить тест shouldSumGenreTwoGames

_Ожидаемый результат_: 5 часов
_Фактический результат_:  0 часов

# Скриншот
![Screenshot_2](https://user-images.githubusercontent.com/104067981/179956506-ac9b72f7-ed3c-4adf-b239-e29874cc69a7.jpg)

# Окружение
- **Операционная система**: Windows 10 Домашняя
- **IDE**: IntelliJ IDEA Community Edition 2022.1.2
- **Java**: OpenJDK 11

**Comment by unicornfraaa** [comment]
fixed
![image](https://user-images.githubusercontent.com/105659262/180056983-847326ec-a5e9-44dc-91e6-c0c2b7c43bdb.png)
