### ISSUE TITLE
В методе play исключение RuntimeException отсутствует

### ISSUE THREAD

**Issue by FairyGreta** [unicornfraaa/Java---TeamProject#8]
# Описание
Метод play не выбрасывает исключение, если игра не установлена. Строки с кодом на исключение отсутствуют

# Локация
[https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L33-L41](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L33-L41)

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/unicornfraaa/Java---TeamProject/blob/b1aeb392af913b1bdbc4b4f351a7e6da6ee45cb2/src/main/java/ru/netology/Player.java#L33-L41) в IDEA;
1. Запустить тест shouldThrowRunTimeException

_Ожидаемый результат_: выпадает исключение
_Фактический результат_:  исключение не найдено

# Скриншот
![Screenshot_3](https://user-images.githubusercontent.com/104067981/179967285-7bac3fb3-d563-46d4-a501-da6675c60f1c.jpg)

# Окружение
- **Операционная система**: Windows 10 Домашняя
- **IDE**: IntelliJ IDEA Community Edition 2022.1.2
- **Java**: OpenJDK 11

**Comment by unicornfraaa** [comment]
fixed
![image](https://user-images.githubusercontent.com/105659262/180058040-777cd567-a015-445f-9394-e94d1f25eb2f.png)
